### ISSUE TITLE
The build fails on my windows 7 system. 

### ISSUE THREAD

**Issue by Vutsuak16** [lowmess/metalsmith-resume#10]
PFA the debug.log file
Are there any dependencies to install?

![capture](https://cloud.githubusercontent.com/assets/10365536/16945031/f90da684-4dc0-11e6-97a8-e10c87d2b360.PNG)

**Comment by lowmess** [comment]
I don't have a Windows machine to test on, but the most likely issue is the nested dependencies. I'd recommend upgrading to node 5.x+ (via nvm or otherwise), as npm 3.x+ uses a flat dependency tree. Windows has a file path length limit that can make node very hard to work with.

**Comment by lowmess** [comment]
@Vutsuak16 on second thought, this *may* have something to do with the teensy-tiny amount of bash in my npm scripts. Have you been able to test with an updated node/npm? If it still fails, I'll work out a more cross-platform fix.

**Comment by lowmess** [comment]
@Vutsuak16 OK, on [the `develop` branch](https://github.com/lowmess/metalsmith-resume/tree/develop), there is a fix that *should* work. If you would be so kind as to test, that would be great! If not, I'll try and track down a Windows machine over the weekend.

**Comment by Vutsuak16** [comment]
It does not work @lowmess  even with updated node :)

**Comment by lowmess** [comment]
This should be fixed in master now. I'm happy to re-open the issue if there are still build issues.
