### ISSUE TITLE
add ability to ignore / 'comment out' specific jobs and schools

### ISSUE THREAD

**Issue by phivk** [lowmess/metalsmith-resume#19]
I would like the ability to adjust my resume to different potential employers. I want to keep job descriptions available in their md files, but have the ability to exclude them easily from the current build.

this could be easily done through a YAML metadata field, e.g. `published: false` and then list jobs / schools in their respective templates unless `published` is set to `false`
Idea would be that by default `published` is considered `true`, so it wouldn't break existing functionality.

**Comment by phivk** [comment]
I created this PR 
https://github.com/lowmess/metalsmith-resume/pull/20

**Comment by lowmess** [comment]
I'm already leveraging [`metalsmith-drafts`](https://github.com/segmentio/metalsmith-drafts) elsewhere in the build, so I've added the ability to use that for this as well. Basically, just add `draft: true` to any item you don't want to publish.

**Comment by phivk** [comment]
cool! I'm unfamiliar with metalsmith features, so didn't know about `drafts`
works like a charm!
